### ISSUE TITLE
The forward pass breaks if `"data_preprocessing"` is absent in config

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/GaNDLF#266]
**Describe the bug**
See title.

**To Reproduce**
1. Have a config without `"data_preprocessing"` present
2. See error:
```python-traceback
Traceback (most recent call last):
  File "/path/to/GaNDLF/gandlf_run", line 87, in <module>
    args.inputdata, args.config, args.modeldir, args.train, args.device, args.resetprev
  File "/gpfs/fs001/path/to/GaNDLF/GANDLF/cli/main_run.py", line 88, in main_run
    reset_prev=reset_prev,
  File "/gpfs/fs001/path/to/GaNDLF/GANDLF/training_manager.py", line 230, in TrainingManager
    testing_data=testingData,
  File "/gpfs/fs001/path/to/GaNDLF/GANDLF/compute/training_loop.py", line 429, in training_loop
    model, val_dataloader, scheduler, params, epoch, mode="validation"
  File "/gpfs/fs001/path/to/GaNDLF/GANDLF/compute/forward_pass.py", line 287, in validate_network
    if "resample" in params["data_preprocessing"]:
TypeError: argument of type 'NoneType' is not iterable
```

**Expected behavior**
This error should not be triggered.

**Screenshots**
N.A.

**GaNDLF Version**

0.0.14-dev

**Desktop (please complete the following information):**
 - OS: N.A.
 - Version: N.A.

**Additional context**
Reported by Ahmed.

**Comment by sarthakpati** [comment]
I am unable to replicate this error on my machine. It should be managed by this line:
https://github.com/CBICA/GaNDLF/blob/63f3d8e9716f2fcea088b231b9c5cbf42306cff2/GANDLF/parseConfig.py#L404

Reaching out to original reporter to see if there is something missing.

**Comment by sarthakpati** [comment]
> ```
> if "resample" in params["data_preprocessing"]:
> ```

Fixed.
