### ISSUE TITLE
`torch==1.11` does not work

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/GaNDLF#417]
**Describe the bug**
GaNDLF codebase is currently not working for `torch==1.11`

**To Reproduce**
1. Update version requirement to `torch==1.11` in `setup.py`
2. Perform installation as specified
3. Try to run any training job
4. See error:
```python-traceback
Traceback (most recent call last):
  File "/cbica/home/patis/comp_space/testing/gandlf_torch-1.11/gandlf_run", line 116, in <module>
    args.reset,
  File "/gpfs/fs001/cbica/comp_space/patis/testing/gandlf_torch-1.11/GANDLF/cli/main_run.py", line 78, in main_run
    reset=reset,
  File "/gpfs/fs001/cbica/comp_space/patis/testing/gandlf_torch-1.11/GANDLF/training_manager.py", line 335, in TrainingManager_split
    testing_data=None,
  File "/gpfs/fs001/cbica/comp_space/patis/testing/gandlf_torch-1.11/GANDLF/compute/training_loop.py", line 404, in training_loop
    model, train_dataloader, optimizer, params
  File "/gpfs/fs001/cbica/comp_space/patis/testing/gandlf_torch-1.11/GANDLF/compute/training_loop.py", line 94, in train_network
    tqdm(memory_safe_data_loader, desc="Looping over training data")
  File "/cbica/comp_space/patis/testing/gandlf_torch-1.11/venv/lib/python3.7/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/cbica/comp_space/patis/testing/gandlf_torch-1.11/venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/cbica/comp_space/patis/testing/gandlf_torch-1.11/venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 570, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/cbica/comp_space/patis/testing/gandlf_torch-1.11/venv/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/cbica/comp_space/patis/testing/gandlf_torch-1.11/venv/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 157, in default_collate
    return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
  File "/cbica/comp_space/patis/testing/gandlf_torch-1.11/venv/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 157, in <dictcomp>
    return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
  File "/cbica/comp_space/patis/testing/gandlf_torch-1.11/venv/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 157, in default_collate
    return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
  File "/cbica/comp_space/patis/testing/gandlf_torch-1.11/venv/lib/python3.7/site-packages/torchio/data/image.py", line 641, in __init__
    super().__init__(*args, **kwargs)
  File "/cbica/comp_space/patis/testing/gandlf_torch-1.11/venv/lib/python3.7/site-packages/torchio/data/image.py", line 156, in __init__
    self.path = self._parse_path(path)
  File "/cbica/comp_space/patis/testing/gandlf_torch-1.11/venv/lib/python3.7/site-packages/torchio/data/image.py", line 419, in _parse_path
    return [self._parse_single_path(p) for p in path]
  File "/cbica/comp_space/patis/testing/gandlf_torch-1.11/venv/lib/python3.7/site-packages/torchio/data/image.py", line 419, in <listcomp>
    return [self._parse_single_path(p) for p in path]
  File "/cbica/comp_space/patis/testing/gandlf_torch-1.11/venv/lib/python3.7/site-packages/torchio/data/image.py", line 409, in _parse_single_path
    raise FileNotFoundError(f'File not found: "{path}"')
FileNotFoundError: File not found: "data"
```

**Expected behavior**
The dataloader should work

**Screenshots**
N.A.

**GaNDLF Version**

0.0.14-dev

**Desktop (please complete the following information):**
 - OS: N.A.
 - Version (including Build information, if any): N.A.

**Additional context**
N.A.

**Comment by sarthakpati** [comment]
This seems to be fixed with https://github.com/fepegar/torchio/pull/838, which seems to be available from `torchio>=0.18.75`.

**Comment by sarthakpati** [comment]
> This seems to be fixed with [fepegar/torchio#838](https://github.com/fepegar/torchio/pull/838), which seems to be available from `torchio>=0.18.75`.

Tested this successfully. I am keeping this issue open till we transition to the new version.

**Comment by sarthakpati** [comment]
https://github.com/Geeks-Sid/GaNDLF/commit/9f51f038a83f8afd7c533bd50ba897b146e44cc8 should fix this.
